### PR TITLE
At pull request data

### PR DESCRIPTION
**Pull request by ahsun-tariq**
In this PR, we have added a job to fetch data about pull requests. The data is stored in the table repo_pull_requests_events. As an instructor, you can download the CSV file about the PR data and also view the number of pull requests on the projects' repo page. Please revisit this code if/when the fields are changed or a different inclusion criteria is required. Presently, the inclusion criteria for PRs is based on three assumptions:

1. The student has given consent.
2. The PR has been closed.
3. The PR has been merged.

### CODE REVIEW

**Comment by pconrad** [comment]
On the QA site, I ran the job on ucsb-cs156-f20 and got this error:

```
Done. Results:
{
  "project_repos": [
    {
      "name": "proj-ucsb-courses-search",
      "result": "Exception: 
undefined method `title=' for #\n\n[\n  \"/app/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.3/lib/active_model/attribute_methods.rb:430:in `method_missing'\",\n  \"/app/app/jobs/repo/course_github_repo_get_pull_requests.rb:99:in `update_one_pull_request'\",\n  \"/app/app/jobs/repo/course_github_repo_get_pull_requests.rb:47:in `store_one_pull_request_in_database'\",\n  \"/app/app/jobs/repo/course_github_repo_get_pull_requests.rb:39:in `block in store_pull_requests_in_database'\",\n  \"/app/app/jobs/repo/course_github_repo_get_pull_requests.rb:34:in `each'\",\n  \"/app/app/jobs/repo/course_github_repo_get_pull_requests.rb:34:in `store_pull_requests_in_database'\",\n  \"/app/app/jobs/repo/course_github_repo_get_pull_requests.rb:24:in `attempt_job'\",\n  \"/app/app/jobs/course_github_repo_job.rb:22:in `block in perform'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'\",\n  \"/app/app/jobs/course_github_repo_job.rb:17:in `perform'\",\n  \"/app/app/jobs/course/refresh_project_repo_pull_requests_job.rb:26:in `process_repo'\",\n  \"/app/app/jobs/course/refresh_project_repo_pull_requests_job.rb:18:in `block in iterate_over_project_repos'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/relation/delegation.rb:71:in `each'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/relation/delegation.rb:71:in `each'\",\n  \"/app/app/jobs/course/refresh_project_repo_pull_requests_job.rb:17:in `iterate_over_project_repos'\",\n  \"/app/app/jobs/course/refresh_project_repo_pull_requests_job.rb:8:in `attempt_job'\",\n  \"/app/app/jobs/course_job.rb:30:in `block in perform'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'\",\n  \"/app/app/jobs/course_job.rb:26:in `perform'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/sucker_punch-2.1.2/lib/sucker_punch/job.rb:60:in `__run_perform'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/sucker_punch-2.1.2/lib/sucker_punch/job.rb:38:in `block in perform_async'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'\"\n]
"
    },
    {
      "name": "proj-mapache-search",
      "result": "Exception: 
undefined method `title=' for #\n\n[\n  \"/app/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.3/lib/active_model/attribute_methods.rb:430:in `method_missing'\",\n  \"/app/app/jobs/repo/course_github_repo_get_pull_requests.rb:99:in `update_one_pull_request'\",\n  \"/app/app/jobs/repo/course_github_repo_get_pull_requests.rb:47:in `store_one_pull_request_in_database'\",\n  \"/app/app/jobs/repo/course_github_repo_get_pull_requests.rb:39:in `block in store_pull_requests_in_database'\",\n  \"/app/app/jobs/repo/course_github_repo_get_pull_requests.rb:34:in `each'\",\n  \"/app/app/jobs/repo/course_github_repo_get_pull_requests.rb:34:in `store_pull_requests_in_database'\",\n  \"/app/app/jobs/repo/course_github_repo_get_pull_requests.rb:24:in `attempt_job'\",\n  \"/app/app/jobs/course_github_repo_job.rb:22:in `block in perform'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'\",\n  \"/app/app/jobs/course_github_repo_job.rb:17:in `perform'\",\n  \"/app/app/jobs/course/refresh_project_repo_pull_requests_job.rb:26:in `process_repo'\",\n  \"/app/app/jobs/course/refresh_project_repo_pull_requests_job.rb:18:in `block in iterate_over_project_repos'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/relation/delegation.rb:71:in `each'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/relation/delegation.rb:71:in `each'\",\n  \"/app/app/jobs/course/refresh_project_repo_pull_requests_job.rb:17:in `iterate_over_project_repos'\",\n  \"/app/app/jobs/course/refresh_project_repo_pull_requests_job.rb:8:in `attempt_job'\",\n  \"/app/app/jobs/course_job.rb:30:in `block in perform'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'\",\n  \"/app/app/jobs/course_job.rb:26:in `perform'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/sucker_punch-2.1.2/lib/sucker_punch/job.rb:60:in `__run_perform'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/sucker_punch-2.1.2/lib/sucker_punch/job.rb:38:in `block in perform_async'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'\"\n]
"
    },
    {
      "name": "proj-ucsb-cs-las",
      "result": "Exception: 
undefined method `title=' for #\n\n[\n  \"/app/vendor/bundle/ruby/2.6.0/gems/activemodel-5.2.4.3/lib/active_model/attribute_methods.rb:430:in `method_missing'\",\n  \"/app/app/jobs/repo/course_github_repo_get_pull_requests.rb:99:in `update_one_pull_request'\",\n  \"/app/app/jobs/repo/course_github_repo_get_pull_requests.rb:47:in `store_one_pull_request_in_database'\",\n  \"/app/app/jobs/repo/course_github_repo_get_pull_requests.rb:39:in `block in store_pull_requests_in_database'\",\n  \"/app/app/jobs/repo/course_github_repo_get_pull_requests.rb:34:in `each'\",\n  \"/app/app/jobs/repo/course_github_repo_get_pull_requests.rb:34:in `store_pull_requests_in_database'\",\n  \"/app/app/jobs/repo/course_github_repo_get_pull_requests.rb:24:in `attempt_job'\",\n  \"/app/app/jobs/course_github_repo_job.rb:22:in `block in perform'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'\",\n  \"/app/app/jobs/course_github_repo_job.rb:17:in `perform'\",\n  \"/app/app/jobs/course/refresh_project_repo_pull_requests_job.rb:26:in `process_repo'\",\n  \"/app/app/jobs/course/refresh_project_repo_pull_requests_job.rb:18:in `block in iterate_over_project_repos'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/relation/delegation.rb:71:in `each'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/relation/delegation.rb:71:in `each'\",\n  \"/app/app/jobs/course/refresh_project_repo_pull_requests_job.rb:17:in `iterate_over_project_repos'\",\n  \"/app/app/jobs/course/refresh_project_repo_pull_requests_job.rb:8:in `attempt_job'\",\n  \"/app/app/jobs/course_job.rb:30:in `block in perform'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'\",\n  \"/app/app/jobs/course_job.rb:26:in `perform'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/sucker_punch-2.1.2/lib/sucker_punch/job.rb:60:in `__run_perform'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/sucker_punch-2.1.2/lib/sucker_punch/job.rb:38:in `block in perform_async'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'\",\n  \"/app/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'\"\n]
"
    }
  ]
}
```

**Comment by pconrad** [comment]
Link to the page showing the error message:

https://ucsb-cs-github-linker-qa.herokuapp.com/courses/49/jobs

**Comment by ahsun-tariq** [comment]
Did we run rails db:migrate?

**Comment by pconrad** [comment]
> Did we run rake db:migrate?

That seems to be exactly the issue... Ahsun and I worked on this, and I think as long as you run rake db:migrate Immediately after deploying, it seems to work.  We are going to try merging it now and see what happens in production.  Wish us luck.

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
